### ISSUE TITLE
Please update to import @hotwired/stimulus instead of stimulus

### ISSUE THREAD

**Issue by mattes3** [robbevp/stimulus-transition#104]
Hi, I wanted to use this library. However, it is compiled against a module called 'stimulus'. I compile against '@hotwired/stimulus'. Could you please update and use the new Stimulus package?

Thanks a lot!

**Comment by robbevp** [comment]
Hi @mattes3 ,

Sorry for the late reply - I was rather busy with some other projects. 
Because of the naming change from `stimulus` to `@hotwired/stimulus`, there is no good way for me to keep support for both stimulus 2 and 3 at the same time. Note that the stimulus package does little more than repackage `@hotwired/stimulus`, so there should be little issue adding `stimulus` as a dependency to your project.

You could also add do the following in your package.json dependencies:
```
"stimulus": "npm:@hotwired/stimulus@3.1.0"
```

**Comment by davidjr82** [comment]
I think it make sense to stay close to the actual stimulus version. Why not create a branch for v2 and set the default for the latest stimulus version (v3 at the moment)? Just my two cents. In my case, I just copy/paste the controller within my project to use it.

Thanks!

**Comment by Petercopter** [comment]
This library is fantastic, thanks so much. I'm using it to implement the transitions from Tailwind UI.

I wasn't able to get it work until I read this issue, it would be great if it got updated to use `@hotwired/stimulus`, that was really confusing!

**Comment by robbevp** [comment]
I've added a note to the readme, so it easier to discover the solution for this.

As mentioned earlier, I want to keep support for stimulus 2.x until their is a technical reason not to do this. It does not make sense to me to have two versions of such a simple package as this one - simply because of another package that changed it name.

**Comment by alec-c4** [comment]
Hey!
Thanks a lot for your library, but I'd like to propose how to manage support for both stimulus 2 and 3
1 - you can create separate branches in your git repo, master/main will point to 3.x version, but branch named 2.x will point to 2.x version
2 - you can create versions in npm catalog, I mean stimulus-transition@2 will support stimulus 2.x, but stimulus-transition@latest will support stimulus 3.x
